apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lobby-server
  template:
    metadata:
      labels:
        app: lobby-server
    spec:
      containers:
      - name: lobby-server
        image: re5nardo/lobby-server:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: lobby-server-config
        - secretRef:
            name: postgres-secret